### ISSUE TITLE
Automated NuGet package creation

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow.MongoDB#5]
Please setup automated builds for the repo, making it possible for others to contribute as well.

I would prefer if you could add me as owner as well (https://www.nuget.org/profiles/rasmus) as I would really like this to be an success and would like to pass it on if @warren-pieterse and @janfeyen is maintaining the repo.

**Comment by rasmus** [comment]
I can setup the build using appveyor, but the `appveyor.yml` file will need to be present.

**Comment by janfeyen** [comment]
I'll have a look over the weekend, new to AppVeyor but I'll give it a go

**Comment by edwardwilson** [comment]
Same here, new to AppVeyor but will be any help I can be if it is needed

**Comment by rasmus** [comment]
I have created a user named eventflow on NuGet.org and will see if its possible to move EventFlow from my personal account to some org on AppVeyor.

Also, I have requested some additional all tools open source license from JetBrains if you are committing time to the project.

**Comment by rasmus** [comment]
Project added https://ci.appveyor.com/project/eventflow/eventflow-mongodb

**Comment by edwardwilson** [comment]
@rasmus I need to look at getting this setup in appveyor now I have a build working.

I can see that in EventFlow there is a deploy for nuget in the `appveyor.yml`:

``` yml
deploy:
  - provider: NuGet
    api_key:
      secure: +YlrKmWps7RJVPU4s7B4HWNL9cZXaUVdiNJInli9IZPlTP+J0CyHsUvcDY8haE+b
    skip_symbols: false
    on:
      branch: master
```

Do we need a different `api_key`?
